/* -*- Mode: C; Character-encoding: utf-8; -*- */

/* Copyright (C) 2004-2019 beingmeta, inc.
   This file is part of the libu8 UTF-8 unicode library.

   This program comes with absolutely NO WARRANTY, including implied
   warranties of merchantability or fitness for any particular
   purpose.

    Use, modification, and redistribution of this program is permitted
    under any of the licenses found in the the 'licenses' directory
    accompanying this distribution, including the GNU General Public License
    (GPL) Version 2 or the GNU Lesser General Public License.
*/

#ifndef LIBU8_U8RANDOM_H
#define LIBU8_U8RANDOM_H 1
#define LIBU8_U8RANDOM_H_VERSION __FILE__

/** Returns a random integer between 0 and n-1 (inclusive)
    @param n the upper limit for the random number
    @returns an int between 0 and n-1
**/
U8_EXPORT unsigned int u8_random(unsigned int n);

/** Sets the random seed value used for the random number generation.
     Setting the random seed value to the same value will cause the sequence
     of numbers generated by u8_random to be the same.
    @param seed the seed value
    @returns void
**/
U8_EXPORT void u8_randomize(unsigned int seed);

#endif
