#!/bin/sh
U8BIN=${U8BIN:-scripts/}
OUTPUT=${1:-../source.tar}
git archive -o ${OUTPUT} HEAD;
cat etc/base_version > BASE_VERSION
scripts/u8_gitversion etc/base_version > VERSION
scripts/u8_gitversion etc/base_version full > FULL_VERSION
scripts/u8_gitbranch > BRANCH
echo ${VERSION%-*} > REL_VERSION
cut -d '.' -f1 < etc/base_version > MAJOR_VERSION
cut -d '.' -f2 < etc/base_version > MINOR_VERSION
tar -rf ${OUTPUT} BASE_VERSION VERSION FULL_VERSION REL_VERSION BRANCH


