#!/bin/sh
PACKAGE=${1:-libu8};
CODENAME=${2:-debian};
STATUS=${3:-stable};
BRANCH=${4:-default};
URGENCY=${5:-medium};
DATE=`date -R`;
gitid=`git describe`;
version=`git describe | sed -e "s/-g[0123456789ABCDEFabcdef]*$//" | sed -e "s/^${PACKAGE}-//"`;
if [ -z "${STATUS}" ] || 
   [ ${STATUS} = "stable" ] || 
   [ ${STATUS} = "default" ]; then
    STATUS=
else
    STATUS="-${STATUS}";
fi;
if [ -z "${BRANCH}" ] || \
   [ ${BRANCH} = "trunk"] || \
   [ ${BRANCH} = "master"] || \
   [ ${BRANCH} = "default"]; then
    BRANCH=
else
    BRANCH="-${BRANCH}";
fi;
echo ${PACKAGE} \(${version}-${CODENAME}\) ${CODENAME}${BRANCH}${STATUS}\; urgency=${URGENCY}
echo
echo "  * ${gitid} point release of ${PACKAGE} for ${CODENAME} (${STATUS})"
echo
echo " -- Repository Manager <repoman@beingmeta.com>  ${DATE}"
echo
cat -
