#!/bin/sh
if ! git status 2>/dev/null 1>/dev/null; then
   if [ -n "${DEFAULT_GITBRANCH}" ]; then echo ${DEFAULT_GITBRANCH}; fi;
   exit;
fi
branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
echo ${branch_name:-main}
