#!/bin/sh
usage() {
    echo "Usage: u8_xsubst <infile> <outfile> [<str> <replace>]...";
}
if [ $# -lt 2 ]; then
    usage;
    return;
fi
INPUT=$1
shift;
OUTPUT=$1
shift;
if [ "${OUTPUT}" = "inplace" ]; then
    OUTPUT=${INPUT};
fi
cp $INPUT $OUTPUT.tmp;
EDIT_ARGS=
while [ $# -gt 1 ]; do
    find=$1; replace=$2; shift; shift;
    EDIT_EXPR="s/@${find}@/${replace}/g"
    EDIT_ARGS="${EDIT_ARGS} -e ${EDIT_EXPR}";
    done;
#echo EDIT_ARGS=${EDIT_ARGS}
if [ ! -z "${EDIT_ARGS}" ]; then
    sed -i ${EDIT_ARGS} ${OUTPUT}.tmp
else
    echo "No substitutions on command line";
    exit;
fi;
if [ ! -f ${OUTPUT} ]; then
    echo ${OUTPUT} created;
    mv $OUTPUT.tmp $OUTPUT;
elif diff ${OUTPUT} ${OUTPUT}.tmp > /dev/null; then
    echo ${OUTPUT} unchanged;
    rm ${OUTPUT}.tmp;
else
    echo ${OUTPUT} updated;
    mv $OUTPUT.tmp $OUTPUT;
fi;

